# This is a basic workflow to help you get started with Actions

name: Update Website

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    tags:
      - v*
      # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update-website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get deps
        run: |
          # Latest version of https://mustache.github.io/ for bash as of 18/9/22
          curl -sSL https://raw.githubusercontent.com/tests-always-included/mo/67ba8bae2cd5dd5a820568bd233ff7ee10406cb7/mo -o mo
          chmod +x ./mo
      - name: Generate HTML
        run: |
          cat www/index.html | VERSION=$(npm pkg get version | sed 's/"//g') ./mo > index.html
          cat index.html
      - name: Upload HTML
        uses: oracle-actions/run-oci-cli-command@v1.1
        env:
          OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
          OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
          OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
          OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
          OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}
        with:
          command: os object put -bn micropad-www --file index.html --content-type text/html --force

  publish-snap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Promote snap to stable
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_TOKEN }}
        run: |
          snapcraft release micropad $(snapcraft list-revisions micropad | awk 'NR==2 {print $1}') stable
