# This is a basic workflow to help you get started with Actions

name: Update Website

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    tags:
      - v*
      # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  update-website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get deps
        run: |
          # Latest version of https://mustache.github.io/ for bash as of 18/9/22
          curl -sSL https://raw.githubusercontent.com/tests-always-included/mo/67ba8bae2cd5dd5a820568bd233ff7ee10406cb7/mo -o mo
          chmod +x ./mo
      - name: Generate HTML
        run: |
          cat www/index.html | VERSION=$(npm pkg get version | sed 's/"//g') ./mo > index.html
          cat index.html
      - name: Upload HTML
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          DEPLOY_PORT: ${{ secrets.DEPLOY_PORT }}
          DEPLOY_DEST: ${{ secrets.DEPLOY_DEST }}
        run: |
          eval `ssh-agent -s`
          echo "$DEPLOY_KEY" | ssh-add -
          scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -P $DEPLOY_PORT index.html "$DEPLOY_DEST"
